{
  # Import all pluging configs
  imports = [
    ./alpha.nix
    ./bufferline.nix
    ./cmp.nix
    ./copilot-lua.nix
    ./dbt-nvim.nix
    ./gitsigns.nix
    ./lualine.nix
    ./mkdnflow.nix
    ./navic.nix
    ./neogit.nix
    ./neorg.nix
    ./noice.nix
    ./notify.nix
    ./nvim-tree.nix
    ./octo-nvim.nix
    ./rainbow-delimiters.nix
    ./render-markdown.nix
    ./rustaceanvim.nix
    ./telescope.nix
    ./todo-comments.nix
    ./treesitter.nix
    ./trim.nix
    ./trouble.nix
    ./undotree.nix
    ./web-devicons.nix
    ./yabt-nvim.nix
  ];
}
